/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as NeedRouteImport } from './routes/need'
import { Route as MyRoleRouteImport } from './routes/my-role'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterEmailRouteImport } from './routes/newsletter_.email'
import { Route as NewsletterSlugRouteImport } from './routes/newsletter_.$slug'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedRoute = NeedRouteImport.update({
  id: '/need',
  path: '/need',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoleRoute = MyRoleRouteImport.update({
  id: '/my-role',
  path: '/my-role',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterEmailRoute = NewsletterEmailRouteImport.update({
  id: '/newsletter_/email',
  path: '/newsletter/email',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterSlugRoute = NewsletterSlugRouteImport.update({
  id: '/newsletter_/$slug',
  path: '/newsletter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/my-role': typeof MyRoleRoute
  '/need': typeof NeedRoute
  '/newsletter': typeof NewsletterRoute
  '/partnership': typeof PartnershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/newsletter/email': typeof NewsletterEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/my-role': typeof MyRoleRoute
  '/need': typeof NeedRoute
  '/newsletter': typeof NewsletterRoute
  '/partnership': typeof PartnershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
  '/newsletter/email': typeof NewsletterEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/my-role': typeof MyRoleRoute
  '/need': typeof NeedRoute
  '/newsletter': typeof NewsletterRoute
  '/partnership': typeof PartnershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/newsletter_/$slug': typeof NewsletterSlugRoute
  '/newsletter_/email': typeof NewsletterEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/my-role'
    | '/need'
    | '/newsletter'
    | '/partnership'
    | '/sitemap.xml'
    | '/story'
    | '/newsletter/$slug'
    | '/newsletter/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/my-role'
    | '/need'
    | '/newsletter'
    | '/partnership'
    | '/sitemap.xml'
    | '/story'
    | '/newsletter/$slug'
    | '/newsletter/email'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/my-role'
    | '/need'
    | '/newsletter'
    | '/partnership'
    | '/sitemap.xml'
    | '/story'
    | '/newsletter_/$slug'
    | '/newsletter_/email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MyRoleRoute: typeof MyRoleRoute
  NeedRoute: typeof NeedRoute
  NewsletterRoute: typeof NewsletterRoute
  PartnershipRoute: typeof PartnershipRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  NewsletterSlugRoute: typeof NewsletterSlugRoute
  NewsletterEmailRoute: typeof NewsletterEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/need': {
      id: '/need'
      path: '/need'
      fullPath: '/need'
      preLoaderRoute: typeof NeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-role': {
      id: '/my-role'
      path: '/my-role'
      fullPath: '/my-role'
      preLoaderRoute: typeof MyRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter_/email': {
      id: '/newsletter_/email'
      path: '/newsletter/email'
      fullPath: '/newsletter/email'
      preLoaderRoute: typeof NewsletterEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter_/$slug': {
      id: '/newsletter_/$slug'
      path: '/newsletter/$slug'
      fullPath: '/newsletter/$slug'
      preLoaderRoute: typeof NewsletterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MyRoleRoute: MyRoleRoute,
  NeedRoute: NeedRoute,
  NewsletterRoute: NewsletterRoute,
  PartnershipRoute: PartnershipRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  NewsletterSlugRoute: NewsletterSlugRoute,
  NewsletterEmailRoute: NewsletterEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
