/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as NeedRouteImport } from './routes/need'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsletterSlugRouteImport } from './routes/newsletter.$slug'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const NeedRoute = NeedRouteImport.update({
  id: '/need',
  path: '/need',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterSlugRoute = NewsletterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsletterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/need': typeof NeedRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/need': typeof NeedRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/mission': typeof MissionRoute
  '/need': typeof NeedRoute
  '/newsletter': typeof NewsletterRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/newsletter/$slug': typeof NewsletterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/mission'
    | '/need'
    | '/newsletter'
    | '/partnership'
    | '/sitemap.xml'
    | '/story'
    | '/newsletter/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/mission'
    | '/need'
    | '/newsletter'
    | '/partnership'
    | '/sitemap.xml'
    | '/story'
    | '/newsletter/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/mission'
    | '/need'
    | '/newsletter'
    | '/partnership'
    | '/sitemap.xml'
    | '/story'
    | '/newsletter/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  MissionRoute: typeof MissionRoute
  NeedRoute: typeof NeedRoute
  NewsletterRoute: typeof NewsletterRouteWithChildren
  PartnershipRoute: typeof PartnershipRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/need': {
      id: '/need'
      path: '/need'
      fullPath: '/need'
      preLoaderRoute: typeof NeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/$slug': {
      id: '/newsletter/$slug'
      path: '/$slug'
      fullPath: '/newsletter/$slug'
      preLoaderRoute: typeof NewsletterSlugRouteImport
      parentRoute: typeof NewsletterRoute
    }
  }
}

interface NewsletterRouteChildren {
  NewsletterSlugRoute: typeof NewsletterSlugRoute
}

const NewsletterRouteChildren: NewsletterRouteChildren = {
  NewsletterSlugRoute: NewsletterSlugRoute,
}

const NewsletterRouteWithChildren = NewsletterRoute._addFileChildren(
  NewsletterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  MissionRoute: MissionRoute,
  NeedRoute: NeedRoute,
  NewsletterRoute: NewsletterRouteWithChildren,
  PartnershipRoute: PartnershipRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
